:PROPERTIES:
:ID:       b242dcc5-4af4-462a-85fb-96d3fb1b5805
:mtime:    20230206181516 20221222172744
:ctime:    20221222165414
:END:
#+title: chezmoi

chezmoi init
  creates a new git local repository in ~/.local/share/chezmoi

chezmoi add <file>
  copy <file> to ~/.local/share/chezmoi/dot_<file>

chezmoi edit <file>
  open ~/.local/share/chezmoi/dot_<file> in $EDITOR

chezmoi diff

chezmoi -v apply

chezmoi cd
  goes to the local repositiory




Getting started

    chezmoi doctor checks for common problems. If you encounter something unexpected, run this first.

    chezmoi init creates chezmoi's source directory and a git repo on a new machine.

Daily commands

    chezmoi add $FILE adds $FILEfrom your home directory to the source directory.

    chezmoi edit $FILE opens your editor with the file in the source directory that corresponds to $FILE.

    chezmoi status gives a quick summary of what files would change if you ran chezmoi apply.

    chezmoi diff shows the changes that chezmoi apply would make to your home directory.

    chezmoi apply updates your dotfiles from the source directory.

    chezmoi edit --apply $FILE is like chezmoi edit $FILE but also runs chezmoi apply $FILE afterwards.

    chezmoi cd opens a subshell in the source directory.

sequenceDiagram participant H as home directory participant W as working copy participant L as local repo participant R as remote repo H->>W: chezmoi add <file> W->>W: chezmoi edit <file> W-->>H: chezmoi status W-->>H: chezmoi diff W->>H: chezmoi apply W->>H: chezmoi edit --apply <file> H-->>W: chezmoi cd
Using chezmoi across multiple machines

    chezmoi init $GITHUB_USERNAME clones your dotfiles from GitHub into the source directory.

    chezmoi init --apply $GITHUB_USERNAME clones your dotfiles from GitHub into the source directory and runs chezmoi apply.

    chezmoi update pulls the latest changes from your remote repo and runs chezmoi apply.

    Use normal git commands to add, commit, and push changes to your remote repo.

sequenceDiagram participant H as home directory participant W as working copy participant L as local repo participant R as remote repo R->>W: chezmoi init <github-username> R->>H: chezmoi init --apply <github-username> R->>H: chezmoi update <github-username> W->>L: git commit L->>R: git push
Working with templates

    chezmoi data prints the available template data.

    chezmoi add --template $FILE adds $FILE as a template.

    chezmoi chattr +template $FILE makes an existing file a template.

    chezmoi cat $FILE prints the target contents of $FILE, without changing $FILE.

    chezmoi execute-template is useful for testing and debugging templates.
