010-160

id,question,answer | answer2,explanation,extra,choice | choice2 | choice3,reversed | choices,tags
id question answer explanation extra choices reversed-choices
* Added
:PROPERTIES:
:TABLE_EXPORT_FILE: lpi-linux-010-160.csv
:TABLE_EXPORT_FORMAT: orgtbl-to-csv
:END:

| 010-160-1 | What are the differences between hard disk drives and solid state disks? (Choose two.)                                  | A. Hard disks have a motor and moving parts, solid state disks do not. \vert E. Solid state disks provide faster access to stored data than hard disks. |   |   | B. Hard disks can fail due to physical damage, while solid state disks cannot fail. \vert C. Solid state disks can store many times as much data as hard disk drives. \vert D. /dev/sda is a hard disk device while /dev/ssda is a solid state disk. |   | 010-160 |
| 010-160-2 | Reverse DNS assigns hostnames to IP addresses. How is the name of the IP address 198.51.100.165 stored on a DNS server? | B. In the RNAME record for 198-51-100-165.rev.arpa.                                                                                                 |   |   | A. In the A record for 165.100.51.198.ipv4.arpa. \vert C. In the ARPA record for 165.100.51.198.rev. \vert D. In the REV record for arpa.in-addr.198.51.100.165.                 |   | 010-160 |
| 010-160-3 | What information can be displayed by top?                                                                               | B. Running processes, ordered by CPU or RAM consumption.                                                                                            |   |   | A. Existing files, ordered by their size. \vert C. User accounts, ordered by the number of logins. \vert D. User groups, ordered by the number of members. \vert E. User accounts, ordered by the number of files. |   | 010-160 |
| 010-160-4 | Which of the following commands can be used to resolve a DNS name to an IP address?                                     | D. host                                                                                                                                             |   |   | A. dnsname \vert B. dns \vert C. query \vert E. iplookup                                                                                                                             |   | 010-160 |
| 010-160-5 | Which of the following outputs comes from the command free?                                                             | E. total used free shared buff/cache available  Mem: 16123128 12565680 2011624 412128 1545824 7180416                                               |   |   | A. A. 21:04:15 up 14 days, 7:43, 3 users, load average: 0.89, 1.00, 0.99 \vert B. avg-cpu: %user %nice %system %iowait %steal %idle  34.04 0.03  13.88   1.06    0.00    50.99 \vert C. Filesystem Size Used Avail Use% Mounted on&emsp /dev/mapper/vg_ssd-root  25G   20G   3.6G   85%   / \vert D. 1.8M   /tmp |   | 010-160 |

QUESTION 6
What is the UID of the user root?
A. 1
B. -1
C. 255
D. 65536
E. 0
Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:
QUESTION 7
What is true about the owner of a file?



A. Each file is owned by exactly one user and one group.
B. The owner of a file always has full permissions when accessing the file.
C. The user owning a file must be a member of the file’s group.
D. When a user is deleted, all files owned by the user disappear.
E. The owner of a file cannot be changed once it is assigned to an owner.
Correct Answer: A
Section: (none)
Explanation
Explanation/Reference:
QUESTION 8
What information is stored in /etc/passwd? (Choose three.)
A. The user’s storage space limit
B. The numerical user ID
C. The username
D. The encrypted password
E. The user\s default shell
Correct Answer: BCE
Section: (none)
Explanation
Explanation/Reference:
QUESTION 9
Which of the following tar options handle compression? (Choose two.)
A. -bz
B. -z
C. -g
D. -j
E. -z2




Correct Answer: BD
Section: (none)
Explanation
Explanation/Reference:
QUESTION 10
Which of the following keys can be pressed to exit less?
A. l
B. x
C. e
D. q
E. !
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:
QUESTION 11
Which of the following commands sorts the output of the command export-logs?
A. export-logs < sort
B. export-logs > sort
C. export-logs & sort
D. export-logs | sort
E. export-logs <> sort
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:




QUESTION 12
A directory contains the following files:

What would be the output of the following shell script?
for file in *.txt

A. *.txt
B. a b
C. c.cav
D. a.txt
E. a. txt
b. txt
Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:
QUESTION 13
Which of the following commands will search for the file foo.txt under the directory /home?
A. search /home –file foo.txt
B. search /home foo. txt
C. find /home – file foo.txt
D. find /home –name foo.txt



E. find /home foo.txt
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:
QUESTION 14
The current directory contains the following file:
-rw-r—r— 1 root exec 24551 Apr 2 12:36 test.sh
The file contains a valid shell script, but executing this file using ./test.sh leads to this error:
bash: ./test.sh: Permission denied
What should be done in order to successfully execute the script?
A. The file’s extension should be changed from .sh to .bin.
B. The execute bit should be set in the file’s permissions.
C. The user executing the script should be added to the exec group.
D. The SetUID bit should be set in the file’s permissions
E. The script should be run using #!./test. sh instead of ./test.sh.
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 15
What is a Linux distribution?
A. The Linux file system as seen from the root account after mounting all file systems.
B. A bundling of the Linux kernel, system utilities and other software.
C. The set of rules which governs the distribution of Linux kernel source code.
D. An operating system based on Linux but incompatible to the regular Linux kernel.



E. A set of changes to Linux which enable Linux to run on another processor architecture.
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 16
Which package management tool is used in Red Hat-based Linux Systems?
A. portage
B. rpm
C. apt-get
D. dpkg
E. packagectl
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 17
Why are web browser cookies considered dangerous?
A. Cookies support identification and tracking of users.
B. Cookies are always public and accessible to anyone on the internet.
C. Cookies consume significant amounts of storage and can exhaust disk space.
D. Cookies store critical data which is lost when a cookie is deleted.
E. Cookies can contain and execute viruses and malware.
Correct Answer: A
Section: (none)
Explanation
Explanation/Reference:



QUESTION 18
Which of the following are typical services offered by public cloud providers? (Choose three.)
A. Platform as a Service(PaaS)
B. Infrastructure as a Service(IaaS)
C. Internet as a Service(IaaS)
D. Graphics as a Service (GaaS)
E. Software as a Service (SaaS)
Correct Answer: ABE
Section: (none)
Explanation
Explanation/Reference:
QUESTION 19
Which of the following characters in a shell prompt indicates the shell is running with root privileges?
A. !
B. #
C. *
D. &
E. $
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 20
What is true about a recursive directory listing?
A. It includes the content of sub-directories.
B. It includes the permissions of the directory listed.



C. It includes details of file system internals, such as inodes.
D. It includes ownership information for the files.
E. It includes a preview of content for each file in the directory.
Correct Answer: A
Section: (none)
Explanation
Explanation/Reference:
QUESTION 21
Which of the following directories contains information, documentation and example configuration files for installed software packages?
A. /usr/share/doc/
B. /etc/defaults/
C. /var/info/
D. /doc/
E. /usr/examples/
Correct Answer: A
Section: (none)
Explanation
Explanation/Reference:
QUESTION 22
Which of the following commands adds the directory /new/dir/ to the PATH environment variable?
A. $PATH=/new/dir: $PATH
B. PATH=/new/dir: PATH
C. export PATH=/new/dir: PATH
D. export $PATH=/new/dir: $PATH
E. export PATH=/new/dir: $PATH
Correct Answer: E
Section: (none)
Explanation



Explanation/Reference:
QUESTION 23
A user is currently in the directory /home/user/Downloads/ and runs the command
ls ../Documents/
Assuming it exists, which directory’s content is displayed?
A. /home/user/Documents/
B. /home/user/Documents/Downloads/
C. /home/user/Downloads/Documents/
D. /Documents/
E. /home/Documents
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:
QUESTION 24
Which of the following is a protocol used for automatic IP address configuration?
A. NFS
B. LDAP
C. SMTP
D. DNS
E. DHCP
Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:




QUESTION 25
Which of the following devices represents a hard disk partition?
A. /dev/ttyS0
B. /dev/sata0
C. /dev/part0
D. /dev/sda2
E. /dev/sda/p2
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:
QUESTION 26
What can be found in the /proc/ directory?
A. One directory per installed program.
B. One device file per hardware device.
C. One file per existing user account.
D. One directory per running process.
E. One log file per running service.
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:
QUESTION 27
A new server needs to be installed to host services for a period of several years. Throughout this time, the server should receive important security updates from its
Linux distribution.
Which of the following Linux distributions meet these requirements? (Choose two.)
A. Ubuntu Linux LTS



B. Fedora Linux
C. Debian GNU/Linux Unstable
D. Ubuntu Linux non-LTS
E. Red Hat Enterprise Linux
Correct Answer: AE
Section: (none)
Explanation
Explanation/Reference:
QUESTION 28
Which of the following directories must be mounted with read and write access if it resides on its own dedicated file system?
A. /opt
B. /lib
C. /etc
D. /var
E. /usr
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:
QUESTION 29
The ownership of the file doku.odt should be changed. The new owner is named tux. Which command accomplishes this change?
A. chmod u=tux doku.odt
B. newuser doku.odt tux
C. chown tux doku.odt
D. transfer tux: doku.odt
E. passwd doku.odt:tux
Correct Answer: C
Section: (none)



Explanation
Explanation/Reference:
QUESTION 30
What happens to a file residing outside the home directory when the file owner's account is deleted? (Choose two.)
A. During a file system check, the file is moved to /lost +found.
B. The file is removed from the file system.
C. The UID of the former owner is shown when listing the file's details.
D. The user root is set as the new owner of the file.
E. Ownership and permissions of the file remain unchanged.
Correct Answer: CE
Section: (none)
Explanation
Explanation/Reference:
QUESTION 31
What is true about links in a Linux file system?
A. A symbolic link can only point to a file and not to a directory.
B. A hard link can only point to a directory and never to a file.
C. When the target of the symbolic link is moved, the link is automatically updated.
D. A symbolic link can point to a file on another file system.
E. Only the root user can create hard links.
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:
QUESTION 32
Which files are the source of the information in the following output? (Choose two.)
uid=1000 (bob) gid=1000 (bob) groups=1000 (bob), 10 (wheel), 150 (wireshark), 989 (docker), 1001 (libvirt)



A. /etc/id
B. /etc/passwd
C. /etc/group
D. /home/index
E. /var/db/users
Correct Answer: BC
Section: (none)
Explanation
Explanation/Reference:
QUESTION 33
Which of the following tasks can the command passwd accomplish? (Choose two.)
A. Change a user's username.
B. Change a user's password.
C. Create a new user account.
D. Create a new user group.
E. Lock a user account.
Correct Answer: CE
Section: (none)
Explanation
Explanation/Reference:
QUESTION 34
Which command displays file names only and no additional information?
A. ls -a
B. ls -lh
C. ls -l
D. ls -alh
E. ls -nl



Correct Answer: A
Section: (none)
Explanation
Explanation/Reference:
QUESTION 35
Which of the following commands puts the lines of the file data.csv into alphabetical order?
A. a..z data.csv
B. sort data.csv
C. abc data.csv
D. wc -s data.csv
E. grep --sort data.csv
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 36
Which of the following examples shows the general structure of a for loop in a shell script?
A. for *.txt as file => echo $file
B. for *.txt ( echo $i )
C. for file in *.txt
do
echo $i
done
D. for ls *.txt exec {} \;
E. foreach @{file} {
echo $i
}
Correct Answer: C
Section: (none)



Explanation
Explanation/Reference:
QUESTION 37
What is the return value of a shell script after successful execution?
A. 1
B. 0
C. -1
D. -255
E. 255
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 38
Which of the following statements are true regarding a typical shell script? (Choose two.)
A. It has the executable permission bit set.
B. It starts with the two character sequence #!.
C. It is located in /usr/local/scripts/.
D. It is located in /etc/bash/scripts/.
E. It is compiled into a binary file compatible with the current machine architecture.
Correct Answer: AE
Section: (none)
Explanation
Explanation/Reference:
QUESTION 39
Which of the following commands extracts the contents of the compressed archive file1.tar.gz?



A. tar -czf file1.tar.gz
B. ztar file1.tar.gz
C. tar -xzf file1.tar.gz
D. tar --extract file1.tar.gz
E. detar file1.tar.gz
Correct Answer: C
Section: (none)
Explanation
Explanation/Reference:
QUESTION 40
Which of the following commands finds all lines in the file operating-systems.txt which contain the term linux, regardless of the case?
A. igrep linux operating-systems.txt
B. less -i linux operating-systems.txt
C. grep -i linux operating-systems.txt
D. cut linux operating-systems.txt
E. cut [Ll] [Ii] [Nn] [Uu] [Xx] operating-systems.txt
Correct Answer: C
Section: (none)
Explanation
Explanation/Reference:
QUESTION 41
Which of the following programs are web servers? (Choose two.)
A. Apache HTTPD
B. Postfix
C. Curl
D. Dovecot
E. NGINX



Correct Answer: AE
Section: (none)
Explanation
Explanation/Reference:
QUESTION 42
Which of the following Linux Distributions is derived from Red Hat Enterprise Linux?
A. Raspbian
B. openSUSE
C. Debian
D. Ubuntu
E. CentOS
Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:
QUESTION 43
What are the differences between a private web browser window and a regular web browser window? (Choose three.)
A. Private web browser windows do not allow printing or storing websites.
B. Private web browser windows do not store cookies persistently.
C. Private web browser windows do not support logins into websites.
D. Private web browser windows do not keep records in the browser history.
E. Private web browser windows do not send regular stored cookies.
Correct Answer: BDE
Section: (none)
Explanation
Explanation/Reference:




QUESTION 44
What is the preferred source for the installation of new applications in a Linux based operating system?
A. The vendor's version management system
B. A CD-ROM disk
C. The distribution's package repository
D. The vendor's website
E. A retail store
Correct Answer: C
Section: (none)
Explanation
Explanation/Reference:






010-160.18q
Number: 010-160
Passing Score: 800
Time Limit: 120 min

010-160



Linux Essentials Certificate Exam, version 1.6



Exam A
QUESTION 1
What information can be displayed by top?
A. Existing files, ordered by their size.
B. Running processes, ordered by CPU or RAM consumption.
C. User accounts, ordered by the number of logins.
D. User groups, ordered by the number of members.
E. User accounts, ordered by the number of files.
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 2
Which of the following commands can be used to resolve a DNS name to an IP address?
A. dnsname
B. dns
C. query
D. host
E. iplookup
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:
QUESTION 3
Which of the following outputs comes from the command free?




A.
B.

C.

D.
E.

Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:
QUESTION 4
Which of the following outputs could stem from the command last?
A. 1 ls
2 cat text.txt
3 logout



B. Password for user last changed at Sat Mar 31 16:38:57 EST 2018
C. Last login: Fri Mar 23 10:56:39 2018 from server.example.com
D. EXT4-fs (dm-7): mounted filesystem with ordered data mode. Opts: (null)
tty2
Wed May 17 21:11 - 21:11
(00:00)
E. root
Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:
QUESTION 5
Which permissions are set on a regular file once the permissions have been modified with the command chmod 654 file.txt?
A. drw-r-xr-B. d—wxr-x-C. –wxr-x--x
D. –rwxrw---x
E. -rw-r-xr-Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:
QUESTION 6
Which of the following permissions are set on the /tmp/ directory?
A. rwxrwxrwt
B. ------rwX
C. rwSrw-rwD. rwxrwS--E. r-xr-X--t
Correct Answer: A



Section: (none)
Explanation
Explanation/Reference:
QUESTION 7
Which command adds the new user tux and creates the user’s home directory with default configuration files?
A. defaultuser tux
B. useradd –m tux
C. usercreate tux
D. useradd –o default tux
E. passwd –a tux
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 8
Which of the following commands creates an archive file work.tar from the contents of the directory ./work/?
A. tar --new work.tar ./work/
B. tar –cf work.tar ./work/
C. tar –create work.tgz –content ./work/
D. tar work.tar < ./work/
E. tar work > work.tar
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 9



Which of the following keys can be pressed to exit less?
A. l
B. x
C. e
D. q
E. !
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:
QUESTION 10
The current directory contains the following file:
-rwxr-xr-x 1 root root 859688 Feb 7 08:15 test.sh
Given that the file is a valid shell script, how can this script be executed? (Choose two correct answers.)
A. run test.sh
B. ${test.sh}
C. cmd ./test.sh
D. ./test.sh
E. bash test.sh
Correct Answer: DE
Section: (none)
Explanation
Explanation/Reference:
QUESTION 11
Which of the following commands sorts the output of the command export-logs?
A. export-logs < sort



B. export-logs > sort
C. export-logs & sort
D. export-logs | sort
E. export-logs <> sort
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:
QUESTION 12
Which package management tool is used in Red Hat-based Linux Systems?
A. portage
B. rpm
C. apt-get
D. dpkg
E. packagectl
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 13
Which of the following programs is a graphical editor for vector graphics?
A. Python
B. NGINX
C. Samba
D. Inkscape
E. MySQL
Correct Answer: D



Section: (none)
Explanation
Explanation/Reference:
QUESTION 14
Where is the operating system of a Raspberry Pi stored?
A. On the master device attached to the Raspberry Pi’s IDE bus.
B. On a read only partition on the Raspberry Pi’s firmware, next to the BIOS.
C. On a removable SD card which is put into the Raspberry Pi.
D. On a Linux extension module connected to the Raspberry Pi’s GPIO pins.
E. On rewritable flash storage which is built into the Raspberry Pi.
Correct Answer: C
Section: (none)
Explanation
Explanation/Reference:
QUESTION 15
What is defined by a Free Software license?
A. Details of the technical documentation each contributor has to provide.
B. The programming languages which may be used to extend the licensed program.
C. A complete list of libraries required to compile the licensed software.
D. Limits on the purposes for which the licensed software may be used.
E. Conditions for modifying and distributing the licensed software.
Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:
QUESTION 16



Why are web browser cookies considered dangerous?
A. Cookies support identification and tracking of users.
B. Cookies are always public and accessible to anyone on the internet.
C. Cookies consume significant amounts of storage and can exhaust disk space.
D. Cookies store critical data which is lost when a cookie is deleted.
E. Cookies can contain and execute viruses and malware.
Correct Answer: A
Section: (none)
Explanation
Explanation/Reference:
QUESTION 17
Which of the following characters in a shell prompt indicates the shell is running with root privileges?
A. !
B. #
C. *
D. &
E. $
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 18
What is true about a recursive directory listing?
A. It includes the content of sub-directories.
B. It includes the permissions of the directory listed.
C. It includes details of file system internals, such as inodes.
D. It includes ownership information for the files.



E. It includes a preview of content for each file in the directory.
Correct Answer: A
Section: (none)
Explanation
Explanation/Reference:





010-160
Number: 010-160
Passing Score: 800
Time Limit: 120 min
File Version: 1

010-160





Exam A
QUESTION 1
What are the differences between hard disk drives and solid state disks? (Choose two.)
A. Hard disks have a motor and moving parts, solid state disks do not.


B. Hard disks can fail due to physical damage, while solid state disks cannot fail.
C. Solid state disks can store many times as much data as hard disk drives.
D. /dev/sda is a hard disk device while /dev/ssda is a solid state disk.
E. Solid state disks provide faster access to stored data than hard disks.
Correct Answer: AE
Section: (none)
Explanation
Explanation/Reference:
QUESTION 2
Reverse DNS assigns hostnames to IP addresses. How is the name of the IP address 198.51.100.165 stored on a DNS server?
A. In the A record for 165.100.51.198.ipv4.arpa.
B. In the PTR record for 165.100.51.198.in-addr.arpa.
C. In the RNAME record for 198-51-100-165.rev.arpa.
D. In the ARPA record for 165.100.51.198.rev.
E. In the REV record for arpa.in-addr.198.51.100.165.
Correct Answer: B
Section: (none)
Explanation



Explanation/Reference:
QUESTION 3
Which of the following outputs comes from the command free?
A.
B.

C.

D.
E.

Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:
QUESTION 4
Which permissions are set on a regular file once the permissions have been modified with the command chmod 654 file.txt?
A. drw-r-xr-B. d—wxr-x-C. –wxr-x--x
D. –rwxrw---x



E. -rw-r-xr-Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:
QUESTION 5
What is true about the owner of a file?
A. Each file is owned by exactly one user and one group.
B. The owner of a file always has full permissions when accessing the file.
C. The user owning a file must be a member of the file’s group.
D. When a user is deleted, all files owned by the user disappear.
E. The owner of a file cannot be changed once it is assigned to an owner.
Correct Answer: A
Section: (none)
Explanation
Explanation/Reference:
QUESTION 6
Which of the following permissions are set on the /tmp/ directory?
A. rwxrwxrwt
B. ------rwX
C. rwSrw-rwD. rwxrwS--E. r-xr-X--t
Correct Answer: A
Section: (none)
Explanation



Explanation/Reference:
QUESTION 7
Which command adds the new user tux and creates the user’s home directory with default configuration files?
A. defaultuser tux
B. useradd –m tux
C. usercreate tux
D. useradd –o default tux
E. passwd –a tux
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 8
What information is stored in /etc/passwd? (Choose three.)
A. The user’s storage space limit
B. The numerical user ID
C. The username
D. The encrypted password
E. The user\s default shell
Correct Answer: BCD
Section: (none)
Explanation
Explanation/Reference:
QUESTION 9
Which of the following tar options handle compression? (Choose two.)
A. -bz



B. -z
C. -g
D. -j
E. -z2
Correct Answer: BD
Section: (none)
Explanation
Explanation/Reference:
QUESTION 10
Which of the following commands creates an archive file work.tar from the contents of the directory ./work/?
A. tar --new work.tar ./work/
B. tar –cf work.tar ./work/
C. tar –create work.tgz –content ./work/
D. tar work.tar < ./work/
E. tar work > work.tar
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 11
Which of the following keys can be pressed to exit less?
A. l
B. x
C. e
D. q
E. !
Correct Answer: D



Section: (none)
Explanation
Explanation/Reference:
QUESTION 12
A directory contains the following files:

What would be the output of the following shell script?
for file in *.txt

A. *.txt
B. a b
C. c.cav
D. a.txt
E. a. txt
b. txt
Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:



QUESTION 13
Which of the following commands will search for the file foo.txt under the directory /home?
A. search /home –file foo.txt
B. search /home foo. txt
C. find /home – file foo.txt
D. find /home –name foo.txt
E. find /home foo.txt
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:
QUESTION 14
The current directory contains the following file:
-rw-r—r— 1 root exec 24551 Apr 2 12:36 test.sh
The file contains a valid shell script, but executing this file using ./test.sh leads to this error:
bash: ./test.sh: Permission denied
What should be done in order to successfully execute the script?
A. The file’s extension should be changed from .sh to .bin.
B. The execute bit should be set in the file’s permissions.
C. The user executing the script should be added to the exec group.
D. The SetUID bit should be set in the file’s permissions
E. The script should be run using #!./test. sh instead of ./test.sh.
Correct Answer: B
Section: (none)
Explanation



Explanation/Reference:
QUESTION 15
Which of the following programs is a graphical editor for vector graphics?
A. Python
B. NGINX
C. Samba
D. Inkscape
E. MySQL
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:
QUESTION 16
Where is the operating system of a Raspberry Pi stored?
A. On the master device attached to the Raspberry Pi’s IDE bus.
B. On a read only partition on the Raspberry Pi’s firmware, next to the BIOS.
C. On a removable SD card which is put into the Raspberry Pi.
D. On a Linux extension module connected to the Raspberry Pi’s GPIO pins.
E. On rewritable flash storage which is built into the Raspberry Pi.
Correct Answer: C
Section: (none)
Explanation
Explanation/Reference:
QUESTION 17
What is defined by a Free Software license?
A. Details of the technical documentation each contributor has to provide.



B. The programming languages which may be used to extend the licensed program.
C. A complete list of libraries required to compile the licensed software.
D. Limits on the purposes for which the licensed software may be used.
E. Conditions for modifying and distributing the licensed software.
Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:
QUESTION 18
Which of the following are typical services offered by public cloud providers? (Choose three.)
A. Platform as a Service(PaaS)
B. Infrastructure as a Service(IaaS)
C. Internet as a Service(IaaS)
D. Graphics as a Service (GaaS)
E. Software as a Service (SaaS)
Correct Answer: ABE
Section: (none)
Explanation
Explanation/Reference:
QUESTION 19
Which of the following commands adds the directory /new/dir/ to the PATH environment variable?
A. $PATH=/new/dir: $PATH
B. PATH=/new/dir: PATH
C. export PATH=/new/dir: PATH
D. export $PATH=/new/dir: $PATH
E. export PATH=/new/dir: $PATH
Correct Answer: E



Section: (none)
Explanation
Explanation/Reference:
QUESTION 20
A directory contains the following three files:
texts 1.txt
texts 2.txt
texts 3.csv
Which command copies the two files ending in .txt to the /tmp/ directory?
A. cp ??.txt /tmp/
B. cp *.txt /tmp/
C. cp. \.txt /tmp/
D. cp ?.txt /tmp/
E. cp $?.txt /tmp/
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:





010-160
Number: 010-160
Passing Score: 800
Time Limit: 120 min
File Version: 1

010-160






Exam A
QUESTION 1
What are the differences between hard disk drives and solid state disks? (Choose two.)


A. Hard disks have a motor and moving parts, solid state disks do not.
B. Hard disks can fail due to physical damage, while solid state disks cannot fail.
C. Solid state disks can store many times as much data as hard disk drives.
D. /dev/sda is a hard disk device while /dev/ssda is a solid state disk.
E. Solid state disks provide faster access to stored data than hard disks.
Correct Answer: AE
Section: (none)
Explanation
Explanation/Reference:
QUESTION 2
Which of the following types of bus can connect hard disk drives with the motherboard?
A. The RAM bus
B. The NUMA bus
C. The CPU bus
D. The SATA bus
E. The Auto bus
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:



QUESTION 3
Members of a team already have experience using Red Hat Enterprise Linux. For a small hobby project, the team wants to set up a Linux server without paying for
a subscription. Which of the following Linux distributions allows the team members to apply as much of their Red Hat Enterprise Linux knowledge as possible?
A. Ubuntu Linux LTS
B. Raspbian
C. Debian GNU/Linux
D. CentOS
E. openSUSE
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:
QUESTION 4
Which of the following outputs comes from the command free?
A.
B.

C.

D.
E.




Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:
QUESTION 5
Which of the following outputs could stem from the command last?
A. 1 ls
2 cat text.txt
3 logout
B. Password for user last changed at Sat Mar 31 16:38:57 EST 2018
C. Last login: Fri Mar 23 10:56:39 2018 from server.example.com
D. EXT4-fs (dm-7): mounted filesystem with ordered data mode. Opts: (null)
tty2
Wed May 17 21:11 - 21:11
(00:00)
E. root
Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:
QUESTION 6
What is the UID of the user root?
A. 1
B. -1
C. 255
D. 65536
E. 0
Correct Answer: E
Section: (none)
Explanation




Explanation/Reference:
QUESTION 7
Which permissions are set on a regular file once the permissions have been modified with the command chmod 654 file.txt?
A. drw-r-xr-B. d—wxr-x-C. –wxr-x--x
D. –rwxrw---x
E. -rw-r-xr-Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:
QUESTION 8
Which command adds the new user tux and creates the user’s home directory with default configuration files?
A. defaultuser tux
B. useradd –m tux
C. usercreate tux
D. useradd –o default tux
E. passwd –a tux
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 9
Which of the following keys can be pressed to exit less?
A. l



B. x
C. e
D. q
E. !
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:
QUESTION 10
The current directory contains the following file:
-rwxr-xr-x 1 root root 859688 Feb 7 08:15 test.sh
Given that the file is a valid shell script, how can this script be executed? (Choose two.)
A. run test.sh
B. ${test.sh}
C. cmd ./test.sh
D. ./test.sh
E. bash test.sh
Correct Answer: DE
Section: (none)
Explanation
Explanation/Reference:
QUESTION 11
A directory contains the following files:




What would be the output of the following shell script?
for file in *.txt

A. *.txt
B. a b
C. c.cav
D. a.txt
E. a. txt
b. txt
Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:
QUESTION 12
Which of the following commands will search for the file foo.txt under the directory /home?
A. search /home –file foo.txt
B. search /home foo. txt
C. find /home – file foo.txt



D. find /home –name foo.txt
E. find /home foo.txt
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:
QUESTION 13
The current directory contains the following file:
-rw-r—r— 1 root exec 24551 Apr 2 12:36 test.sh
The file contains a valid shell script, but executing this file using ./test.sh leads to this error:
bash: ./test.sh: Permission denied
What should be done in order to successfully execute the script?
A. The file’s extension should be changed from .sh to .bin.
B. The execute bit should be set in the file’s permissions.
C. The user executing the script should be added to the exec group.
D. The SetUID bit should be set in the file’s permissions
E. The script should be run using #!./test. sh instead of ./test.sh.
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 14
What is a Linux distribution?
A. The Linux file system as seen from the root account after mounting all file systems.
B. A bundling of the Linux kernel, system utilities and other software.



C. The set of rules which governs the distribution of Linux kernel source code.
D. An operating system based on Linux but incompatible to the regular Linux kernel.
E. A set of changes to Linux which enable Linux to run on another processor architecture.
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 15
Which package management tool is used in Red Hat-based Linux Systems?
A. portage
B. rpm
C. apt-get
D. dpkg
E. packagectl
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 16
Where is the operating system of a Raspberry Pi stored?
A. On the master device attached to the Raspberry Pi’s IDE bus.
B. On a read only partition on the Raspberry Pi’s firmware, next to the BIOS.
C. On a removable SD card which is put into the Raspberry Pi.





D. On a Linux extension module connected to the Raspberry Pi’s GPIO pins.
E. On rewritable flash storage which is built into the Raspberry Pi.
Correct Answer: C
Section: (none)
Explanation
Explanation/Reference:
QUESTION 17
Why are web browser cookies considered dangerous?
A. Cookies support identification and tracking of users.
B. Cookies are always public and accessible to anyone on the internet.
C. Cookies consume significant amounts of storage and can exhaust disk space.
D. Cookies store critical data which is lost when a cookie is deleted.
E. Cookies can contain and execute viruses and malware.
Correct Answer: A
Section: (none)
Explanation
Explanation/Reference:
QUESTION 18
Which of the following characters in a shell prompt indicates the shell is running with root privileges?
A. !
B. #
C. *
D. &
E. $
Correct Answer: B



Section: (none)
Explanation
Explanation/Reference:
QUESTION 19
Which of the following commands are used to get information on the proper use of ls? (Choose two.)
A. option ls
B. usage ls
C. manual ls
D. man ls
E. info ls
Correct Answer: DE
Section: (none)
Explanation
Explanation/Reference:
QUESTION 20
A user is currently in the directory /home/user/Downloads/ and runs the command
ls ../Documents/
Assuming it exists, which directory’s content is displayed?
A. /home/user/Documents/
B. /home/user/Documents/Downloads/
C. /home/user/Downloads/Documents/
D. /Documents/
E. /home/Documents
Correct Answer: D
Section: (none)
Explanation




Explanation/Reference:
QUESTION 21
A directory contains the following three files:
texts 1.txt
texts 2.txt
texts 3.csv
Which command copies the two files ending in .txt to the /tmp/ directory?
A. cp ??.txt /tmp/
B. cp *.txt /tmp/
C. cp. \.txt /tmp/
D. cp ?.txt /tmp/
E. cp $?.txt /tmp/
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 22
Which of the following DNS record types hold an IP address? (Choose two.)
A. NS
B. AAAA
C. MX
D. A
E. CNAME
Correct Answer: CD
Section: (none)
Explanation
Explanation/Reference:



QUESTION 23
Which of the following values could be a process ID on Linux?
A. /bin/bash
B. 60b503cd-019e-4300-a7be-922f074ef5ce
C. /sys/pid/9a14
D. fff3
E. 21398
Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:
QUESTION 24
Which of the following is a protocol used for automatic IP address configuration?
A. NFS
B. LDAP
C. SMTP
D. DNS
E. DHCP
Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:
QUESTION 25
Which of the following statements regarding Linux hardware drivers is correct?
A. Drivers are regular Linux programs which have to be run by the user who wants to use a device.
B. Drivers are not used by Linux because the BIOS handles all access to hardware on behalf of Linux.



C. Drivers are stored on their devices and are copied by the Linux kernel when a new device is attached
D. Drivers are downloaded from the vendor's driver repository when a new device is attached.
E. Drivers are either compiled into the Linux kernel or are loaded as kernel modules.
Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:
QUESTION 26
What can be found in the /proc/ directory?
A. One directory per installed program.
B. One device file per hardware device.
C. One file per existing user account.
D. One directory per running process.
E. One log file per running service.
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:
QUESTION 27
Which of the following directories must be mounted with read and write access if it resides on its own dedicated file system?
A. /opt
B. /lib
C. /etc
D. /var
E. /usr
Correct Answer: D
Section: (none)



Explanation
Explanation/Reference:
QUESTION 28
Which files are the source of the information in the following output? (Choose two.)
uid=1000 (bob) gid=1000 (bob) groups=1000 (bob), 10 (wheel), 150 (wireshark), 989 (docker), 1001 (libvirt)
A. /etc/id
B. /etc/passwd
C. /etc/group
D. /home/index
E. /var/db/users
Correct Answer: BC
Section: (none)
Explanation
Explanation/Reference:
QUESTION 29
Which of the following commands shows the absolute path to the current working directory?
A. who
B. cd ..
C. pwd
D. ls -l
E. cd ~/home
Correct Answer: C
Section: (none)
Explanation
Explanation/Reference:
QUESTION 30



Which of the following commands output the content of the file Texts 2.txt? (Choose two.)
A. cat 'Texts 2.txt’
B. cat -- Texts 2.txt
C. cat |Texts 2.txt|
D. cat 'Texts\ 2.txt’
E. cat Texts\ 2.txt
Correct Answer: AB
Section: (none)
Explanation
Explanation/Reference:
QUESTION 31
Which of the following commands puts the lines of the file data.csv into alphabetical order?
A. a..z data.csv
B. sort data.csv
C. abc data.csv
D. wc -s data.csv
E. grep --sort data.csv
Correct Answer: B
Section: (none)
Explanation
Explanation/Reference:
QUESTION 32
Which of the following commands creates the ZIP archive poems.zip containing all files in the current directory whose names end in .txt?
A. zip *.txt > poems.zip
B. zcat *.txt poems.zip
C. zip poems.zip *.txt
D. zip cfz poems.zip *.txt



E. cat *.txt | zip poems.zip
Correct Answer: C
Section: (none)
Explanation
Explanation/Reference:
QUESTION 33
Which one of the following statements concerning Linux passwords is true?
A. All passwords can be decrypted using the system administrator's master password.
B. Passwords may never start with a non-letter.
C. Users cannot change their password once it has been set.
D. Passwords are only stored in hashed form.
E. Passwords may be at most six characters long.
Correct Answer: D
Section: (none)
Explanation
Explanation/Reference:
QUESTION 34
Which of the following Linux Distributions is derived from Red Hat Enterprise Linux?
A. Raspbian
B. openSUSE
C. Debian
D. Ubuntu
E. CentOS
Correct Answer: E
Section: (none)
Explanation
Explanation/Reference:



QUESTION 35
What are the differences between a private web browser window and a regular web browser window? (Choose three.)
A. Private web browser windows do not allow printing or storing websites.
B. Private web browser windows do not store cookies persistently.
C. Private web browser windows do not support logins into websites.
D. Private web browser windows do not keep records in the browser history.
E. Private web browser windows do not send regular stored cookies.
Correct Answer: BDE
Section: (none)
Explanation
Explanation/Reference:







