#+title: Causal Analysis Essay

* Introduciton

What are the causes behind

is a growing problem in the U.S. today caused primarily by

Social media addiction:
the way social media is designed
the way people use social media
genetics, personality, environment

Social media platforms such as Facebook, Snapchat, and Instagram produce the
same neural circuitry caused by gambling and recreational drugs. A constant
stream of retweets, likes, and shares affects the brain's reward area and
triggers the same kind of chemical reaction as other drugs, such as cocaine.
(Werner Geyser, 2022)

How will this new age designer drug continue to impact the world?

Social media platforms have evolve from a place to kill time to place a that wants all your time.
These platforms continue to evolve to capture a young generation, while almost trying to demand all your time.

These social media platforms continue grow and


Social media addiction is a growing problem around the world caused primarily by
the dopamine release, FOMO, and negative emotions.

* Dopamine release

Social media platforms are designed for Dopamine release.

When a person engages in a pleasurable activity, the brain releases a hormone called dopamine. Dopamine is responsible for feelings of pleasure.()

This dopamine release is similar to the use of recreational drugs and gambling.

An increase in dopamine levels may cur after social media notifications. These
triggering events can be comments, retweets, or other positive events.

The reliance on these positive events caused by the interaction with the social
media platforms may cause an addiction.


* FOMO

FOMO is the fear of missing out. Social media is great at exacerbate that
feeling. By constantly showing what everybody doing. This can lead to feeling
anxiety and insecure. Which can lead to more social media usage to feeling apart
of the loop.

* Negative Emotions

After getting hooked with dopamine releases, then getting stuck in a loop because of
FOMO. People start to cope with negative emotions using social media. Social
media provides a temporary escape from these negative emotions.

* Conclusion

Factors that contribute to social media addiction are the dopamine releases,
FOMO, and negative emotions.  The impact of social media platforms creating a
product which sole goal to cause dopamine releases to addicted a generation. Can
not be understated. The hooked being the addictive design, the FOMO being the
vicious cycle that keeps people coming back. To the ability to use social media
as coping mechichan for negative emotions.

* References
Werner Geyser. (2022). Retrieved from https://influencermarketinghub.com/social-media-addiction-stats/
Suzy Davenport. (2022). Retrieved from https://www.medicalnewstoday.com/articles/social-media-addiction
